import bcrypt from 'bcryptjs';
const data = {
    users: [
        {
            name: 'Basir',
            email: 'kk99351@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'Kundan',
            email: 'kk9935@gmail.com',
            password: bcrypt.hashSync('2345', 8),
            isAdmin: false,
        },
    ],
    products:[
        {
         _id:'1',
         name:'Nike Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 10,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
        },
        {
            _id:'2',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;